cmake_minimum_required(VERSION 3.31)
project(Lab08_2025_2_CSV_Estructuras_Dinamicas)

set(CMAKE_CXX_STANDARD 20)

add_executable(Lab08_2025_2_CSV_Estructuras_Dinamicas main.cpp
        Bibliotecas/FuncionesAuxiliares.cpp
        Bibliotecas/FuncionesAuxiliares.h
        Bibliotecas/Reproduccion.h
        Bibliotecas/Categoria.h)
